version: '2.3'

services:
  utils:
    image: docker-utils:test
    build: .
    entrypoint: /srv/scripts/tail.sh
    environment:
      AWS_PROFILE: stag
    volumes:
    - "~/.gitconfig:/root/.gitconfig"
    - "~/.bash_history:/root/.bash_history"
    - "~/.aws:/root/.aws"
    - "~/.ssh:/root/.ssh"
    - "~/.gnupg:/root/.gnupg"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"